extends: "standard"
plugins:
  - standard
  - react
  - jsx-a11y
parserOptions:
  ecmaFeatures:
    jsx: true
parser: "babel-eslint"
rules:
  no-tabs: 0
  semi: 0
  space-before-function-paren: 0
  react/jsx-no-duplicate-props: 2
  react/jsx-uses-vars: 2
  react/jsx-no-undef: 2
  react/jsx-uses-react: 2
  react/jsx-indent-props:
    - 2
    - 2
  react/no-deprecated: 2
  react/no-direct-mutation-state: 2
  react/no-find-dom-node: 2
  react/no-is-mounted: 2
  react/no-unknown-property: 2
  react/react-in-jsx-scope: 2
  react/require-render-return: 2
  react/prefer-stateless-function: 2
  ##react/prop-types: 2
  jsx-a11y/anchor-has-content: 2
  jsx-a11y/aria-props: 2
  jsx-a11y/aria-proptypes: 2
  jsx-a11y/aria-role: 2
  jsx-a11y/aria-unsupported-elements: 2
  jsx-a11y/click-events-have-key-events: 2
  jsx-a11y/heading-has-content: 2
  jsx-a11y/href-no-hash: 2
  jsx-a11y/html-has-lang: 2
  jsx-a11y/img-has-alt: 2
  jsx-a11y/img-redundant-alt: 2
  jsx-a11y/label-has-for: 2
  jsx-a11y/mouse-events-have-key-events: 2
  jsx-a11y/no-access-key: 2
  jsx-a11y/no-marquee: 2
  jsx-a11y/no-onchange: 2
  jsx-a11y/no-static-element-interactions: 1
  jsx-a11y/onclick-has-focus: 2
  jsx-a11y/onclick-has-role: 2
  jsx-a11y/role-has-required-aria-props: 2
  jsx-a11y/role-supports-aria-props: 2
  jsx-a11y/scope: 2
jsx-a11y/tabindex-no-positive: 1
